{# ===== From php ===== #}
FROM php:{{ php.version | default(__conf.php.version) }}-cli-alpine

{# ===== Install extensions and composer ===== #}
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions @composer{{ php.composer_version ? '-' + php.composer_version : '' }} {{ php.extensions | join(' ') }}

{# ===== Copy php config ===== #}
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
{% if exists('.php.d') %}
  COPY .php.d/ /usr/local/etc/php/conf.d/
{% endif %}

{# ===== Copy project ===== #}
WORKDIR /app
COPY . .

{# ===== Inject dockerfile ===== #}
{{ php.run | join('\n') }}

{# Set cmd #}
{% if php.cmd %}
  CMD {{ php.cmd is iterable ? (php.cmd | json_encode) : php.cmd }}
{% elseif exists('server.php') %}
  CMD ["php", "server.php"]
{% elseif exists('app.php') %}
  CMD ["php", "app.php"]
{% elseif exists('main.php') %}
  CMD ["php", "main.php"]
{% elseif exists('index.php') %}
  CMD ["php", "index.php"]
{% else %}
  CMD ["php"]
{% endif %}
