{# ===== From nginx ===== #}
FROM nginx:{{ nginx.version | default(__conf.nginx.version) }}-alpine

{# ===== Config ===== #}
COPY {{ copy('nginx/nginx.conf.twig') }} /etc/nginx/nginx.conf
{# Extension config #}
{% if exists('.nginx.d') %}
  COPY .nginx.d/ /etc/nginx/conf.d/
{% endif %}

{# ===== Copy project ===== #}
WORKDIR /app
{% set nginx_root = nginx.root | default('public') %}
COPY ./{{ nginx_root }} ./{{ nginx_root }}

{# ===== Inject dockerfile ===== #}
{{ nginx.run | join('\n') }}